default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: ausma_development
  username: ausma
  password: 12345678

test:
  <<: *default
  database: ausma_test
  username: ausma
  password: 12345678

production:
  <<: *default
  database: ausma_production
  username: ausma
  password: <%= ENV['AUSMA_DATABASE_PASSWORD'] %>
